name: Build
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build project
        uses: actions/setup-node@v3
        with:
          node-version: 15.x

      - run: npm install
      - run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nature-of-code
          path: dist
          retention-days: 1